# 这是一个基本的工作流程，可以帮助您开始使用 Actions

名称：CI

# 控制工作流的运行时间
在：
  # 触发推送或拉取请求事件的工作流，但仅限于“main”分支
  推送：
    分支：[ "main" ]
  拉取请求:
    分支：[ "main" ]

  # 允许您从 Actions 标签手动运行此工作流
  工作流派送：

# 工作流运行由一个或多个作业组成，这些作业可以串行或并行运行
工作：
  # 此工作流包含一个名为“build”的作业
  构建：
    # 作业将运行的运行器类型
    运行于：ubuntu-latest

    # 步骤表示一系列将作为作业的一部分执行的任务
    步骤：
      # 将你的仓库检出到 $GITHUB_WORKSPACE，以便你的作业可以访问
      输入：使用：actions/checkout@v4

      # 在runners shell中运行单个命令
      - 名字: 运行一条命令脚本
        运行： echo Hello, world!

      # 在runners shell中运行一组命令
      - 名字: 运行多行脚本
        运行：|
          echo 添加其他操作以进行构建，
          执行测试，并部署您的项目。
